<?php
/**
 * Shared FAQ content for the FAQ page and JSON-LD schema.
 */

if (!defined('ABSPATH')) {
    exit;
}

if (!function_exists('dawp_get_faq_items')) {
    function dawp_get_faq_items() {
        return [
            ['question' => 'Where can I buy Veterangift products?', 'answer' => 'Products shown on Veterangift are available for direct purchase through our online store. Add available items to your cart and complete checkout securely on the website.'],
            ['question' => 'Where do you ship?', 'answer' => 'Veterangift currently ships exclusively within the United States. If a product, address, or carrier limitation prevents delivery to your location, you will be notified at checkout before payment is completed.'],
            ['question' => 'How much does shipping cost and are there hidden fees?', 'answer' => 'Standard U.S. shipping is free on all orders $49 and over. Orders under $49 have a flat $4.99 shipping fee shown at checkout. Applicable U.S. state sales taxes are calculated transparently at checkout before you pay. There are no hidden fees, tariffs, or surprise charges.'],
            ['question' => 'How long does delivery take?', 'answer' => 'Orders are processed in 1-2 business days after purchase. Standard transit usually takes 3-5 business days, so the estimated delivery window is 4-7 business days total from the purchase date.'],
            ['question' => 'What is your order cutoff time?', 'answer' => 'Our order cutoff time is 5:00 PM (GMT-08:00) Pacific Standard Time. Orders placed after the cutoff begin processing on the following business day.'],
            ['question' => 'How do I track my order?', 'answer' => 'After your order ships, we send a shipping confirmation email with a direct tracking link and carrier details. You can also use the <a href="/track-order/">Track Order page</a> with your order number and email address.'],
            ['question' => 'Why did I receive multiple tracking numbers?', 'answer' => 'Orders containing multiple apparel pieces, hats, accessories, or custom gifts may ship separately from different fulfillment batches. Each shipment will have its own tracking number.'],
            ['question' => 'Can I cancel or change my shipping address after placing an order?', 'answer' => 'Please contact customer support as soon as possible if you need to request an address change or cancellation. Once an order enters our automated fulfillment system (typically within 12-24 hours), modifications may no longer be possible.'],
            ['question' => 'When is my order officially accepted?', 'answer' => 'Your order is accepted when our automated system sends a confirmation email to the address provided at checkout. We may refuse, limit, or cancel an order for reasons such as suspected payment fraud, stock discrepancies, pricing errors, or production limitations. If a paid order is canceled by us, the refund is processed to the original payment method.'],
            ['question' => 'Will my printed item look exactly like the product mockup?', 'answer' => 'Because graphic shirts and apparel products may be made to order, minor variations in ink placement, scaling, and color vibrancy can occur. Product images are prepared to be accurate, but final color appearance can also depend on your device and monitor settings.'],
            ['question' => 'Can I change personalized details after placing an order?', 'answer' => 'Customers are responsible for reviewing sizing, spelling, and customization details before checkout. Once a personalized item enters the production queue, design changes may not be possible. Personalized or custom-made items are not eligible for return or exchange unless they arrive defective, damaged, incorrect, or misprinted due to our error.'],
            ['question' => 'What should I do if my package is delayed, lost, or marked delivered but missing?', 'answer' => 'Contact customer support within 30 days of the recorded delivery date or expected delivery issue. Include your order number, checkout email address, full delivery address, and any carrier tracking details so we can investigate.'],
            ['question' => 'What if my item arrives damaged or incorrect?', 'answer' => 'Contact us within 30 days of delivery with your order number and clear photos of the item, packaging, and shipping label. For defective, damaged, incorrect, or carrier-damaged products, we cover 100% of the return shipping cost and arrange the appropriate replacement or refund at no cost to you.'],
            ['question' => 'What is your return window & return method?', 'answer' => 'Eligible return requests must be initiated within 30 days of delivery. All returns are processed <strong>by mail</strong> after obtaining a Return Merchandise Authorization (RMA) from our support team. Items must be unworn, unused, undamaged, and in original packaging.'],
            ['question' => 'Do you charge a restocking fee?', 'answer' => 'No. Veterangift does not charge any restocking fee ($0 restocking fee) for eligible returns.'],
            ['question' => 'Who pays for return shipping?', 'answer' => 'For defective, damaged, incorrect, or carrier-damaged products, Veterangift covers 100% of the return shipping cost and provides a prepaid label by email — you pay nothing. For customer remorse (wrong size, wrong color, changed mind, or does not fit), a flat $4.99 return shipping fee applies and is deducted from your refund.'],
            ['question' => 'When will I receive my refund?', 'answer' => 'After your return package is received, we inspect the item within 1-2 business days. If approved, the refund is issued to your original payment method within 7 business days. If you have not received a refund after 15 business days of approval, please contact us after checking with your bank or card issuer.'],
            ['question' => 'How do I start a return?', 'answer' => 'Email us at <a href="mailto:support@veterangift.com">support@veterangift.com</a> or use the <a href="/contact-us/">Contact Us page</a> within 30 days of delivery. Include your order number, checkout email, item(s) to return, reason for return, and photos if damaged. Do not ship an item back without return authorization.'],
            ['question' => 'Do you offer direct exchanges?', 'answer' => 'We do not offer direct one-to-one exchanges. To exchange an item for a different size, color, or style, please return the original eligible item for a refund and place a new order on our website.'],
            ['question' => 'Which items are non-returnable?', 'answer' => 'Final sale or non-returnable items, gift cards, digital products, personalized or custom-made items (unless defective), hygiene-sensitive items with broken seals, and items worn, washed, altered, or damaged after delivery are not eligible for return.'],
            ['question' => 'Is checkout secure and encrypted?', 'answer' => 'Yes. Checkout uses SSL/TLS encryption for all transaction data through WooCommerce and PCI-DSS certified payment gateways. Veterangift does not store raw credit card numbers on local storefront servers.'],
            ['question' => 'What payment methods are available?', 'answer' => 'We accept major credit cards (Visa, MasterCard, American Express, Discover) and PayPal as displayed during checkout.'],
            ['question' => 'Do you sell or share my personal information?', 'answer' => 'No. We do not sell, rent, or lease your personal information to third parties. We use your data strictly to process payments, fulfill purchases, ship orders, and provide customer support in compliance with our Privacy Policy.'],
            ['question' => 'Do you use cookies?', 'answer' => 'Yes. We use essential cookies for cart persistence, login states, and storefront performance. You can adjust cookies in your browser settings, but disabling essential cookies may affect checkout functionality.'],
            ['question' => 'How can I request access, correction, or deletion of my data?', 'answer' => 'You can email <a href="mailto:support@veterangift.com">support@veterangift.com</a> to request access, correction, updates, or deletion of your personal information where applicable under privacy laws such as GDPR or CCPA.'],
            ['question' => 'How can I contact customer support?', 'answer' => 'Reach us at <a href="mailto:support@veterangift.com">support@veterangift.com</a>, call 901-675-3151, or use the <a href="/contact-us/">Contact Us page</a>. Business address: 1417 Weiner Rd, Memphis, TN 38108. Customer service hours are Monday - Friday, 10:00 AM - 6:00 PM PST, with typical response times within 24 business hours.'],
        ];
    }
}
