<?php
/**
 * Shared FAQ content for the FAQ page and JSON-LD schema.
 */

if (!defined('ABSPATH')) {
    exit;
}

if (!function_exists('dawp_get_faq_items')) {
    function dawp_get_faq_items() {
        return [
            ['question' => 'Where can I buy YourWatchStore watches?', 'answer' => 'Every watch shown on YourWatchStore is available for direct purchase through this online store. Add available items to your cart and complete checkout securely on the website.'],
            ['question' => 'Where do you ship?', 'answer' => 'YourWatchStore currently ships within the United States only. If an address or carrier limitation prevents delivery to your location, you will be notified at checkout before payment is completed.'],
            ['question' => 'How much does shipping cost?', 'answer' => 'Standard US shipping is free on every order. There is no minimum order value and no separate handling fee.'],
            ['question' => 'How long does delivery take?', 'answer' => 'Orders are processed in 1-3 business days after purchase. Standard transit usually takes 3-7 business days, so the estimated delivery window is about 4-10 business days total from the order date.'],
            ['question' => 'What is your order cutoff time?', 'answer' => 'Our order cutoff time is 12:00 PM (Noon) Eastern Time. Orders placed after the cutoff, or on weekends and US public holidays, begin processing on the next business day.'],
            ['question' => 'How do I track my order?', 'answer' => 'After your order ships, we send a shipping confirmation email with a tracking link and carrier details. You can also use the <a href="/track-order/">Track Order page</a> with your order information.'],
            ['question' => 'Why did I receive more than one tracking number?', 'answer' => 'An order with multiple watches or accessories may ship in separate parcels. Each shipment has its own tracking number, and all tracking links are sent to your email as parcels leave our facility.'],
            ['question' => 'Can I change or cancel my order after checkout?', 'answer' => 'Contact us as soon as possible if you need to change or cancel an order. We cannot guarantee changes once an order has entered processing or been handed to the carrier.'],
            ['question' => 'When is my order officially accepted?', 'answer' => 'Your order is accepted when our system sends a confirmation email to the address provided at checkout. We may refuse, limit, or cancel an order for reasons such as suspected payment fraud, stock discrepancies, or pricing errors. If a paid order is canceled by us, the refund is issued to the original payment method.'],
            ['question' => 'Are the watches automatic or do they need a battery?', 'answer' => 'Our core collection is automatic (self-winding) mechanical watches. They wind from the natural motion of your wrist during normal wear and do not use a battery. Each product page lists the specific movement for that watch.'],
            ['question' => 'How do I set and wind an automatic watch?', 'answer' => 'If the watch has stopped, wind the crown around 20-30 turns to build a power reserve, then set the time and date. Worn daily, an automatic watch keeps running on wrist motion. Avoid changing the date between roughly 9:00 PM and 3:00 AM, when the date mechanism is engaged.'],
            ['question' => 'Are the watches water resistant?', 'answer' => 'Water resistance varies by model and is stated on each product page. A rating such as 100m suits swimming, while lower ratings are splash-resistant only. Do not operate the crown or pushers underwater, and have seals checked periodically to maintain the rating.'],
            ['question' => 'What crystal do the watches use?', 'answer' => 'Our core collection uses scratch-resistant sapphire crystal over the dial. The crystal type for each watch is listed in its specifications.'],
            ['question' => 'Can I resize the strap or bracelet myself?', 'answer' => 'Leather and rubber straps use standard spring bars and can be swapped with a spring-bar tool. Metal bracelets are sized by removing links and are best adjusted by a watchmaker or jeweler. Strap and lug width are listed on each product page.'],
            ['question' => 'What should I do if my package is delayed, lost, or marked delivered but missing?', 'answer' => 'Contact customer support within 30 days of the recorded delivery date or expected delivery. Include your order number, checkout email, full delivery address, and any tracking details so we can open an investigation with the carrier.'],
            ['question' => 'What if my watch arrives damaged or is not what I ordered?', 'answer' => 'Contact us within 30 days of delivery with your order number and clear photos of the watch, the packaging, and the shipping label. For defective, damaged, incorrect, or carrier-damaged items, we cover return shipping and arrange a replacement or refund.'],
            ['question' => 'What is your return window?', 'answer' => 'Eligible return requests must be started within 30 days of delivery. The watch must be unworn and in original condition, with all protective stickers, the box, papers, warranty card, and any links or accessories included.'],
            ['question' => 'Do you charge a restocking fee?', 'answer' => 'No. YourWatchStore does not charge restocking fees on eligible returns.'],
            ['question' => 'Who pays for return shipping?', 'answer' => 'For defective, damaged, incorrect, or carrier-damaged watches, YourWatchStore covers return shipping and sends a prepaid label by email. For change-of-mind returns, including "did not suit me" or "found another model," the customer is responsible for return shipping, and that cost may be deducted from the refund.'],
            ['question' => 'When will I receive my refund?', 'answer' => 'Once your return arrives, we inspect the watch within 1-2 business days. If approved, the refund is issued to your original payment method within 7 business days. If you have not seen the refund 15 business days after approval, contact us after checking with your bank or card issuer.'],
            ['question' => 'How do I start a return?', 'answer' => 'Email us or use the <a href="/contact-us/">Contact Us page</a> within 30 days of delivery. Include your order number, checkout email, the item you want to return, the reason, and photos or video if the watch is damaged, defective, or incorrect. Please do not ship anything back before you receive a return authorization.'],
            ['question' => 'Do you offer exchanges?', 'answer' => 'We do not process direct one-for-one exchanges. To switch to a different model, return the original eligible watch for a refund and place a new order on the website.'],
            ['question' => 'Which items are non-returnable?', 'answer' => 'Gift cards, final-sale items, and watches that have been worn, sized, engraved, or damaged after delivery are not eligible for return. Watches missing the box, papers, or warranty card may have the refund reduced.'],
            ['question' => 'Do the watches come with a warranty?', 'answer' => 'Where a manufacturer warranty applies, the warranty card is included in the box and its terms are set by the manufacturer. Separately, we inspect every watch for timekeeping and function before it ships, and any fault present on arrival is covered under our 30-day return policy.'],
            ['question' => 'Is checkout secure?', 'answer' => 'Yes. Checkout uses SSL-encrypted payment transmission through WooCommerce and certified third-party payment gateways. YourWatchStore does not store raw card numbers on its storefront servers.'],
            ['question' => 'What payment methods are available?', 'answer' => 'Available payment methods are shown during checkout before the order is completed. The checkout page displays the full order total, including any applicable tax, before payment is submitted.'],
            ['question' => 'How do you use my personal information?', 'answer' => 'We use order, device, and support information to process payments, fulfill orders, arrange shipping, send order updates, screen transactions for fraud, improve the store, and provide customer support, as described in our <a href="/privacy-policy/">Privacy Policy</a>.'],
            ['question' => 'Do you use cookies?', 'answer' => 'Yes. We use essential cookies for cart persistence, login state, and store performance. You can adjust or clear cookies in your browser settings, but disabling essential cookies may stop checkout from working.'],
            ['question' => 'How can I request access, correction, or deletion of my data?', 'answer' => 'Email <a href="mailto:support@yourwatchstore.com">support@yourwatchstore.com</a> to request access, correction, or deletion of your personal information where applicable under privacy laws such as GDPR or CCPA.'],
            ['question' => 'How can I contact customer support?', 'answer' => 'Reach us at <a href="mailto:support@yourwatchstore.com">support@yourwatchstore.com</a> or through the <a href="/contact-us/">Contact Us page</a>. Our support hours are Monday - Friday, 9:00 AM - 5:00 PM EST, and we typically reply within one business day.'],
        ];
    }
}
