<?php
if (!defined('ABSPATH')) { exit; }
$policy_title = __('Return & Refund Policy', 'dawp');
$policy_intro = __('We want every GraphicShirt order to arrive correctly and in good condition. This policy explains the options available for made-to-order products, damaged or incorrect items, and eligible returns.', 'dawp');
$policy_updated = __('July 22, 2026', 'dawp');
$policy_sections = [
    ['title' => __('1. Return Window and Eligibility', 'dawp'), 'copy' => [__('Contact us within 30 days of delivery to request a return. An item must be unworn, unwashed, unused, and in its original condition, with tags and original packaging where applicable. A receipt or order number is required.', 'dawp'), __('Most GraphicShirt products are printed or produced after an order is placed. Because they are made to order, returns for a change of mind, a preference change, or an incorrectly selected size may be limited. Please review the product description and size guide before ordering.', 'dawp')]],
    ['title' => __('2. Damaged, Defective, or Incorrect Items', 'dawp'), 'copy' => [__('Inspect your order after delivery and contact us promptly if an item is damaged, defective, misprinted, or different from what you ordered. Include your order number and clear photos of the item, packaging, and shipping label.', 'dawp'), __('After review, we will provide an appropriate replacement or refund at no additional cost. In some cases, returning the affected item will not be required.', 'dawp')]],
    ['title' => __('3. How to Request a Return', 'dawp'), 'copy' => [__('Email support@graphicshirt.com with your order number, the item involved, the reason for your request, and photos when the item is damaged or incorrect. Wait for return authorization and instructions before mailing anything. Unauthorized returns may not be accepted.', 'dawp'), __('Pack an authorized return securely and use a trackable shipping service. Do not send returns to an address shown on the original parcel unless our support team confirms it.', 'dawp')]],
    ['title' => __('4. Return Shipping and Fees', 'dawp'), 'copy' => [__('GraphicShirt charges no restocking fee. We cover reasonable return or replacement costs when we made an error or the product arrived damaged or defective.', 'dawp'), __('For an approved return based on customer preference or remorse, the customer is responsible for return shipping and the original shipping charge is non-refundable, except where applicable law requires otherwise.', 'dawp')]],
    ['title' => __('5. Refunds', 'dawp'), 'copy' => [__('We will notify you after an authorized return has been received and inspected. Approved refunds are sent to the original payment method, normally within 7 business days. Your bank or card provider may need additional time to post the credit.', 'dawp'), __('If more than 15 business days have passed since we approved a refund, please contact support so we can investigate.', 'dawp')]],
    ['title' => __('6. Exchanges and Non-returnable Items', 'dawp'), 'copy' => [__('For damaged or incorrect products, we generally arrange a replacement rather than a traditional exchange. For size or preference changes, placing a new order may be the fastest option and eligibility remains subject to the made-to-order terms above.', 'dawp')], 'items' => [__('Worn, washed, altered, or used items.', 'dawp'), __('Items with stains, odors, pet hair, or damage caused after delivery.', 'dawp'), __('Final-sale items and gift cards.', 'dawp'), __('Personalized products, except when defective or incorrectly produced.', 'dawp')]],
];
require locate_template('template-parts/page-policy-layout.php');
